management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  metrics.web.server.request.autotime.percentiles: 0.99,0.95,0.5

logging.level.root: "INFO"

server:
  port: ${PORT:8080}