name: Deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Select tag"
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download jar
        run: 'wget -d --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://maven.pkg.github.com/trident2710/barcode-research/com/trident/barcode-generation-service/${{ inputs.version }}/barcode-generation-service-${{ inputs.version }}.jar'
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku plugins:install heroku-cli-deploy && heroku deploy:jar barcode-generation-service-${{ inputs.version }}.jar --app barcode-research