name: Deploy finite-field-calculator-service to Heroku

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Select tag"
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download jar
        run: 'wget -d --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://maven.pkg.github.com/trident2710/barcode-research/com/trident/finite-field-calculator-service-server/${{ inputs.version }}/finite-field-calculator-service-server-${{ inputs.version }}.jar'
      - name: Install cli deploy plugin
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku plugins:install heroku-cli-deploy
      - name: Make system.properties file
        run: echo 'java.runtime.version=17' > system.properties
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku deploy:jar finite-field-calculator-service-server${{ inputs.version }}.jar --app finite-field-calculator
